# Generated by Django 2.1.7 on 2019-03-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
                ('passport_id', models.CharField(max_length=100)),
                ('fav_geners', models.CharField(max_length=200)),
            ],
        ),
    ]
