# Generated by Django 2.1.7 on 2019-03-31 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_form'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookPost',
            new_name='Book',
        ),
    ]
