# Generated by Django 2.2 on 2019-05-19 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_counter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
