# Generated by Django 2.1.7 on 2019-04-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190409_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(default='Book Description'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(choices=[('av', 'Available'), ('add', 'Added to Library'), ('na', 'Not Available')], default='av', max_length=3),
        ),
    ]
