# Generated by Django 2.1.7 on 2019-04-09 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190409_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='due_back',
            new_name='back_date',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='amound',
        ),
    ]
