# Generated by Django 2.1.7 on 2019-04-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190409_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationform',
            name='fav_geners',
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='registrationform',
            name='genres',
            field=models.ManyToManyField(to='main.Genre'),
        ),
    ]
