# Generated by Django 2.1.7 on 2019-04-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190410_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
