# Generated by Django 2.1.7 on 2019-04-14 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_bookinstance_taken_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationform',
            name='genres',
        ),
        migrations.DeleteModel(
            name='RegistrationForm',
        ),
    ]
