# Generated by Django 2.2 on 2019-05-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fav_genres',
            new_name='favourite_genres',
        ),
        migrations.AlterField(
            model_name='profile',
            name='adress',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passport_id',
            field=models.CharField(max_length=100),
        ),
    ]
