# Generated by Django 2.1.7 on 2019-04-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190414_1530'),
        ('users', '0003_registrationform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationform',
            name='genres',
        ),
        migrations.AddField(
            model_name='profile',
            name='adress',
            field=models.CharField(default='Minsk, Belarus', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='fav_genres',
            field=models.ManyToManyField(to='main.Genre'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='Last Name', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Name', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='passport_id',
            field=models.CharField(default='MP1239023', max_length=100),
        ),
        migrations.DeleteModel(
            name='RegistrationForm',
        ),
    ]
