# Generated by Django 2.1.7 on 2019-04-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190414_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fav_genres',
            field=models.ManyToManyField(blank=True, to='main.Genre'),
        ),
    ]
