//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameStore {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GameStore.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string StatisticsPageTitle {
            get {
                return ResourceManager.GetString("StatisticsPageTitle", resourceCulture);
            }
        }
        
        public static string StatisticsPageTabTitle {
            get {
                return ResourceManager.GetString("StatisticsPageTabTitle", resourceCulture);
            }
        }
        
        public static string LibraryPageTitle {
            get {
                return ResourceManager.GetString("LibraryPageTitle", resourceCulture);
            }
        }
        
        public static string LibraryPageTabTitle {
            get {
                return ResourceManager.GetString("LibraryPageTabTitle", resourceCulture);
            }
        }
        
        public static string ShopPageTitle {
            get {
                return ResourceManager.GetString("ShopPageTitle", resourceCulture);
            }
        }
        
        public static string ShopPageTabTitle {
            get {
                return ResourceManager.GetString("ShopPageTabTitle", resourceCulture);
            }
        }
        
        public static string SearchPageTitle {
            get {
                return ResourceManager.GetString("SearchPageTitle", resourceCulture);
            }
        }
        
        public static string SearchPageTabTitle {
            get {
                return ResourceManager.GetString("SearchPageTabTitle", resourceCulture);
            }
        }
        
        public static string SearchPageInSearchText {
            get {
                return ResourceManager.GetString("SearchPageInSearchText", resourceCulture);
            }
        }
        
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        public static string SettingsPageLangTitle {
            get {
                return ResourceManager.GetString("SettingsPageLangTitle", resourceCulture);
            }
        }
        
        public static string SettingsPageTabTitle {
            get {
                return ResourceManager.GetString("SettingsPageTabTitle", resourceCulture);
            }
        }
        
        public static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        public static string DarkTheme {
            get {
                return ResourceManager.GetString("DarkTheme", resourceCulture);
            }
        }
        
        public static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        public static string TopGames {
            get {
                return ResourceManager.GetString("TopGames", resourceCulture);
            }
        }
        
        public static string Soon {
            get {
                return ResourceManager.GetString("Soon", resourceCulture);
            }
        }
        
        public static string SeeAllGames {
            get {
                return ResourceManager.GetString("SeeAllGames", resourceCulture);
            }
        }
        
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        public static string Metascore {
            get {
                return ResourceManager.GetString("Metascore", resourceCulture);
            }
        }
        
        public static string CriticReviews {
            get {
                return ResourceManager.GetString("CriticReviews", resourceCulture);
            }
        }
        
        public static string CriticReviewsDesc {
            get {
                return ResourceManager.GetString("CriticReviewsDesc", resourceCulture);
            }
        }
        
        public static string LinkToCrit {
            get {
                return ResourceManager.GetString("LinkToCrit", resourceCulture);
            }
        }
        
        public static string UserScore {
            get {
                return ResourceManager.GetString("UserScore", resourceCulture);
            }
        }
        
        public static string UserReviews {
            get {
                return ResourceManager.GetString("UserReviews", resourceCulture);
            }
        }
        
        public static string UserReviewsDesc {
            get {
                return ResourceManager.GetString("UserReviewsDesc", resourceCulture);
            }
        }
        
        public static string LinkToUser {
            get {
                return ResourceManager.GetString("LinkToUser", resourceCulture);
            }
        }
        
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        public static string MetacriticLink {
            get {
                return ResourceManager.GetString("MetacriticLink", resourceCulture);
            }
        }
        
        public static string LinkToGame {
            get {
                return ResourceManager.GetString("LinkToGame", resourceCulture);
            }
        }
        
        public static string AllGames {
            get {
                return ResourceManager.GetString("AllGames", resourceCulture);
            }
        }
        
        public static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        public static string AgeLimit {
            get {
                return ResourceManager.GetString("AgeLimit", resourceCulture);
            }
        }
        
        public static string Platforms {
            get {
                return ResourceManager.GetString("Platforms", resourceCulture);
            }
        }
    }
}
