# Generated by Django 2.2 on 2019-05-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='transaction_date',
            field=models.IntegerField(default=0),
        ),
    ]
